
server:
  port: 7983


spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password: ''
  h2:
    console:
      enabled: true

  jpa:
    hibernate:
      ddi-auto: update
    database-platform: org.hibernate.dialect.H2Dialect

